// AUTOGENERATED by packages/components/scripts/gen-background-docs.mjs.
// Single source of prose: the `description` strings in this directory's
// background.ts (never edit this file by hand — run `pnpm gen`, which the
// build/test/check scripts also run, after changing a description).
/* eslint-disable */

import { type NumberSignalMethod, type StringSignalMethod } from "@moliniani/core";

/**
 * Tween methods exposed by FlowFieldBackground — one per declarative prop. Hover
 * docs mirror the config `description`s verbatim, so `createMnRef()` refs
 * read the same prose as the JSX attributes.
 */
export interface FlowFieldBackgroundSignals {
  /**
   * Backdrop color behind the trails — any CSS color (8-digit hex adds alpha).
   */
  color0: StringSignalMethod;
  /**
   * Palette stop 1 — warm amber. Any CSS color; the color1–color7 defaults form
   * the original amber → gold → coral ramp.
   */
  color1: StringSignalMethod;
  /**
   * Palette stop 2 — gold. Any CSS color (8-digit hex adds alpha).
   */
  color2: StringSignalMethod;
  /**
   * Palette stop 3 — coral. Any CSS color (8-digit hex adds alpha).
   */
  color3: StringSignalMethod;
  /**
   * Palette stop 4 — dark amber. Any CSS color (8-digit hex adds alpha).
   */
  color4: StringSignalMethod;
  /**
   * Palette stop 5 — light gold. Any CSS color (8-digit hex adds alpha).
   */
  color5: StringSignalMethod;
  /**
   * Palette stop 6 — deep coral. Any CSS color (8-digit hex adds alpha).
   */
  color6: StringSignalMethod;
  /**
   * Palette stop 7 — muted gold. Any CSS color (8-digit hex adds alpha).
   */
  color7: StringSignalMethod;
  /**
   * Scales trail stroke alpha. Range 0–2: 0 hides the trails, 1 = original
   * brightness, 2 doubles it (per-particle alpha is 0.15–0.7).
   */
  brightness: NumberSignalMethod;
  /**
   * Number of flowing trail particles. Range 500–5000: fewer = sparse/cheap, more
   * = denser. Cost scales with trailFrames + 1 segments drawn per particle per
   * frame.
   */
  particleCount: NumberSignalMethod;
  /**
   * Spatial frequency of the flow field, in CSS-pixel space. Range 0.0005–0.01:
   * low = broad smooth swirls, high = fine tight detail.
   */
  noiseScale: NumberSignalMethod;
  /**
   * Multiplies the trails' velocity along the field. Range 0–6: 0 freezes the
   * trails, 1.2 = original look, above ~4 the trails smear into long tails.
   */
  speed: NumberSignalMethod;
  /**
   * How many frames each trail persists before fading. Range 8–48: short = crisp
   * streaks, long = ghosty ribbons.
   */
  trailFrames: NumberSignalMethod;
}

/**
 * Declarative props of FlowFieldBackground (JSX attributes and `background(...)`
 * config literals). Carries the per-prop hover docs, mirroring the config
 * `description`s verbatim.
 */
export interface FlowFieldBackgroundProps {
  /**
   * Backdrop color behind the trails — any CSS color (8-digit hex adds alpha).
   */
  color0?: string;
  /**
   * Palette stop 1 — warm amber. Any CSS color; the color1–color7 defaults form
   * the original amber → gold → coral ramp.
   */
  color1?: string;
  /**
   * Palette stop 2 — gold. Any CSS color (8-digit hex adds alpha).
   */
  color2?: string;
  /**
   * Palette stop 3 — coral. Any CSS color (8-digit hex adds alpha).
   */
  color3?: string;
  /**
   * Palette stop 4 — dark amber. Any CSS color (8-digit hex adds alpha).
   */
  color4?: string;
  /**
   * Palette stop 5 — light gold. Any CSS color (8-digit hex adds alpha).
   */
  color5?: string;
  /**
   * Palette stop 6 — deep coral. Any CSS color (8-digit hex adds alpha).
   */
  color6?: string;
  /**
   * Palette stop 7 — muted gold. Any CSS color (8-digit hex adds alpha).
   */
  color7?: string;
  /**
   * Scales trail stroke alpha. Range 0–2: 0 hides the trails, 1 = original
   * brightness, 2 doubles it (per-particle alpha is 0.15–0.7).
   */
  brightness?: number;
  /**
   * Number of flowing trail particles. Range 500–5000: fewer = sparse/cheap, more
   * = denser. Cost scales with trailFrames + 1 segments drawn per particle per
   * frame.
   */
  particleCount?: number;
  /**
   * Spatial frequency of the flow field, in CSS-pixel space. Range 0.0005–0.01:
   * low = broad smooth swirls, high = fine tight detail.
   */
  noiseScale?: number;
  /**
   * Multiplies the trails' velocity along the field. Range 0–6: 0 freezes the
   * trails, 1.2 = original look, above ~4 the trails smear into long tails.
   */
  speed?: number;
  /**
   * How many frames each trail persists before fading. Range 8–48: short = crisp
   * streaks, long = ghosty ribbons.
   */
  trailFrames?: number;
}
