// AUTOGENERATED by packages/components/scripts/gen-background-docs.mjs.
// Single source of prose: the `description` strings in this directory's
// background.ts (never edit this file by hand — run `pnpm gen`, which the
// build/test/check scripts also run, after changing a description).
/* eslint-disable */

import { type NumberSignalMethod, type StringSignalMethod } from "@moliniani/core";

/**
 * Tween methods exposed by KineticGridBackground — one per declarative prop. Hover
 * docs mirror the config `description`s verbatim, so `createMnRef()` refs
 * read the same prose as the JSX attributes.
 */
export interface KineticGridBackgroundSignals {
  /**
   * Connection-line ramp stop 1: dark rust resting color. Any CSS color (alpha is
   * ignored).
   */
  lineColor0: StringSignalMethod;
  /**
   * Connection-line ramp stop 2: low-tension fire orange. Any CSS color (alpha is
   * ignored).
   */
  lineColor1: StringSignalMethod;
  /**
   * Connection-line ramp stop 3: mid-tension bright orange. Any CSS color (alpha
   * is ignored).
   */
  lineColor2: StringSignalMethod;
  /**
   * Connection-line ramp stop 4: high-tension hot orange-white. Any CSS color
   * (alpha is ignored).
   */
  lineColor3: StringSignalMethod;
  /**
   * Connection-line ramp stop 5: white-hot extreme tension. Any CSS color (alpha
   * is ignored).
   */
  lineColor4: StringSignalMethod;
  /**
   * Node-dot ramp stop 1: deep midnight blue at rest. Any CSS color (alpha is
   * ignored).
   */
  nodeColor0: StringSignalMethod;
  /**
   * Node-dot ramp stop 2: electric cyan as nodes pick up speed. Any CSS color
   * (alpha is ignored).
   */
  nodeColor1: StringSignalMethod;
  /**
   * Node-dot ramp stop 3: near-white through fast wavefronts. Any CSS color (alpha
   * is ignored).
   */
  nodeColor2: StringSignalMethod;
  /**
   * Impulse flash color: radial glow core, expanding ring, wavefront halos. Any
   * CSS color (alpha is ignored).
   */
  flashColor: StringSignalMethod;
  /**
   * Persistent backdrop the neon mesh trails over (vignette tints with it). Any
   * CSS color (alpha is ignored — renders opaque).
   */
  backdrop: StringSignalMethod;
  /**
   * Edge-impulse frequency — the grid's heartbeat. Range 0.3–3: 0.3 = mostly
   * still, 0.7 = original pace (~2.6s apart), 3 = constant waves.
   */
  impulseRate: NumberSignalMethod;
  /**
   * Mesh spring stiffness — multiplies the base spring constant. Range 0.2–3: 0.2
   * = loose floppy lattice, 1 = original look, 3 = taut snappy propagation.
   */
  springTension: NumberSignalMethod;
  /**
   * Impulse kick strength on the edge it hits. Range 0.3–3: 0.3 = gentle ripples,
   * 1 = original look, 3 = violent slaps.
   */
  impulseForce: NumberSignalMethod;
  /**
   * Per-frame velocity damping. Range 0.95–0.995: 0.95 = fast settling, 0.978 =
   * original look, 0.995 = long rings after each impulse.
   */
  damping: NumberSignalMethod;
  /**
   * Per-frame pull back toward rest. Range 0.001–0.01: 0.001 = slow drift, 0.003 =
   * original look, 0.01 = taut springy recovery.
   */
  returnForce: NumberSignalMethod;
  /**
   * Grid density — scales the 40x25 node grid. Range 0.5–2: 0.5 = coarse ~20x12
   * shards, 1 = original, 2 = fine 80x50 mesh (heavier to rebuild on scrubs).
   */
  density: NumberSignalMethod;
  /**
   * Neon trail persistence — depth of the ghosted overlay trace. Range 0–40: 0 =
   * crisp no trails, 15 = original look, 40 = long warm streaking.
   */
  trailFrames: NumberSignalMethod;
}

/**
 * Declarative props of KineticGridBackground (JSX attributes and `background(...)`
 * config literals). Carries the per-prop hover docs, mirroring the config
 * `description`s verbatim.
 */
export interface KineticGridBackgroundProps {
  /**
   * Connection-line ramp stop 1: dark rust resting color. Any CSS color (alpha is
   * ignored).
   */
  lineColor0?: string;
  /**
   * Connection-line ramp stop 2: low-tension fire orange. Any CSS color (alpha is
   * ignored).
   */
  lineColor1?: string;
  /**
   * Connection-line ramp stop 3: mid-tension bright orange. Any CSS color (alpha
   * is ignored).
   */
  lineColor2?: string;
  /**
   * Connection-line ramp stop 4: high-tension hot orange-white. Any CSS color
   * (alpha is ignored).
   */
  lineColor3?: string;
  /**
   * Connection-line ramp stop 5: white-hot extreme tension. Any CSS color (alpha
   * is ignored).
   */
  lineColor4?: string;
  /**
   * Node-dot ramp stop 1: deep midnight blue at rest. Any CSS color (alpha is
   * ignored).
   */
  nodeColor0?: string;
  /**
   * Node-dot ramp stop 2: electric cyan as nodes pick up speed. Any CSS color
   * (alpha is ignored).
   */
  nodeColor1?: string;
  /**
   * Node-dot ramp stop 3: near-white through fast wavefronts. Any CSS color (alpha
   * is ignored).
   */
  nodeColor2?: string;
  /**
   * Impulse flash color: radial glow core, expanding ring, wavefront halos. Any
   * CSS color (alpha is ignored).
   */
  flashColor?: string;
  /**
   * Persistent backdrop the neon mesh trails over (vignette tints with it). Any
   * CSS color (alpha is ignored — renders opaque).
   */
  backdrop?: string;
  /**
   * Edge-impulse frequency — the grid's heartbeat. Range 0.3–3: 0.3 = mostly
   * still, 0.7 = original pace (~2.6s apart), 3 = constant waves.
   */
  impulseRate?: number;
  /**
   * Mesh spring stiffness — multiplies the base spring constant. Range 0.2–3: 0.2
   * = loose floppy lattice, 1 = original look, 3 = taut snappy propagation.
   */
  springTension?: number;
  /**
   * Impulse kick strength on the edge it hits. Range 0.3–3: 0.3 = gentle ripples,
   * 1 = original look, 3 = violent slaps.
   */
  impulseForce?: number;
  /**
   * Per-frame velocity damping. Range 0.95–0.995: 0.95 = fast settling, 0.978 =
   * original look, 0.995 = long rings after each impulse.
   */
  damping?: number;
  /**
   * Per-frame pull back toward rest. Range 0.001–0.01: 0.001 = slow drift, 0.003 =
   * original look, 0.01 = taut springy recovery.
   */
  returnForce?: number;
  /**
   * Grid density — scales the 40x25 node grid. Range 0.5–2: 0.5 = coarse ~20x12
   * shards, 1 = original, 2 = fine 80x50 mesh (heavier to rebuild on scrubs).
   */
  density?: number;
  /**
   * Neon trail persistence — depth of the ghosted overlay trace. Range 0–40: 0 =
   * crisp no trails, 15 = original look, 40 = long warm streaking.
   */
  trailFrames?: number;
}
