// AUTOGENERATED by packages/components/scripts/gen-background-docs.mjs.
// Single source of prose: the `description` strings in this directory's
// background.ts (never edit this file by hand — run `pnpm gen`, which the
// build/test/check scripts also run, after changing a description).
/* eslint-disable */

import { type NumberSignalMethod, type StringSignalMethod } from "@moliniani/core";

/**
 * Tween methods exposed by SugarGlassBackground — one per declarative prop. Hover
 * docs mirror the config `description`s verbatim, so `createMnRef()` refs
 * read the same prose as the JSX attributes.
 */
export interface SugarGlassBackgroundSignals {
  /**
   * Primary glass color; each shard blends toward color1. Any CSS color (alpha is
   * ignored — the glass renders opaque).
   */
  color0: StringSignalMethod;
  /**
   * Secondary glass color; shards mix between color0 and color1 per cell. Any CSS
   * color (alpha is ignored).
   */
  color1: StringSignalMethod;
  /**
   * Deep tint pooled in thick shards, keyed off per-cell thickness. Any CSS color
   * (alpha is ignored).
   */
  darkColor: StringSignalMethod;
  /**
   * Warm light that bleeds around fracture lines. Any CSS color (alpha is
   * ignored).
   */
  crackColor: StringSignalMethod;
  /**
   * Brightest core of the crack lines, reached at full crack intensity. Any CSS
   * color (alpha is ignored).
   */
  crackHighlight: StringSignalMethod;
  /**
   * Rose-gold refraction tint near cracks, mixed in at up to ~25%. Any CSS color
   * (alpha is ignored).
   */
  refractColor: StringSignalMethod;
  /**
   * Fracture animation speed — multiplier on scene time. Range 0.1–2: 0.1 =
   * near-static caramel, 0.5 = original look, 2 = fast writing cracks.
   */
  crackSpeed: NumberSignalMethod;
  /**
   * Crack light intensity — scales the bright lines and their glow. Range 0.3–2:
   * 0.3 dims the light, 1 = original look, 2 floods the shards.
   */
  lightBleed: NumberSignalMethod;
  /**
   * Fracture-network density — scales macro and micro Voronoi frequency. Range
   * 0.5–3: 0.5 = fewer, larger shards; 1 = original look; 3 = dense fine cracking.
   */
  density: NumberSignalMethod;
  /**
   * Crack line width — multiplier on the base fracture width. Range 0–2: 0 hides
   * the lines (glow only), 1 = original look, 2 = thick chunky fissures.
   */
  crackWidth: NumberSignalMethod;
}

/**
 * Declarative props of SugarGlassBackground (JSX attributes and `background(...)`
 * config literals). Carries the per-prop hover docs, mirroring the config
 * `description`s verbatim.
 */
export interface SugarGlassBackgroundProps {
  /**
   * Primary glass color; each shard blends toward color1. Any CSS color (alpha is
   * ignored — the glass renders opaque).
   */
  color0?: string;
  /**
   * Secondary glass color; shards mix between color0 and color1 per cell. Any CSS
   * color (alpha is ignored).
   */
  color1?: string;
  /**
   * Deep tint pooled in thick shards, keyed off per-cell thickness. Any CSS color
   * (alpha is ignored).
   */
  darkColor?: string;
  /**
   * Warm light that bleeds around fracture lines. Any CSS color (alpha is
   * ignored).
   */
  crackColor?: string;
  /**
   * Brightest core of the crack lines, reached at full crack intensity. Any CSS
   * color (alpha is ignored).
   */
  crackHighlight?: string;
  /**
   * Rose-gold refraction tint near cracks, mixed in at up to ~25%. Any CSS color
   * (alpha is ignored).
   */
  refractColor?: string;
  /**
   * Fracture animation speed — multiplier on scene time. Range 0.1–2: 0.1 =
   * near-static caramel, 0.5 = original look, 2 = fast writing cracks.
   */
  crackSpeed?: number;
  /**
   * Crack light intensity — scales the bright lines and their glow. Range 0.3–2:
   * 0.3 dims the light, 1 = original look, 2 floods the shards.
   */
  lightBleed?: number;
  /**
   * Fracture-network density — scales macro and micro Voronoi frequency. Range
   * 0.5–3: 0.5 = fewer, larger shards; 1 = original look; 3 = dense fine cracking.
   */
  density?: number;
  /**
   * Crack line width — multiplier on the base fracture width. Range 0–2: 0 hides
   * the lines (glow only), 1 = original look, 2 = thick chunky fissures.
   */
  crackWidth?: number;
}
