// AUTOGENERATED by packages/components/scripts/gen-background-docs.mjs.
// Single source of prose: the `description` strings in this directory's
// background.ts (never edit this file by hand — run `pnpm gen`, which the
// build/test/check scripts also run, after changing a description).
/* eslint-disable */

import { type NumberSignalMethod, type StringSignalMethod } from "@moliniani/core";

/**
 * Tween methods exposed by TopographicBackground — one per declarative prop. Hover
 * docs mirror the config `description`s verbatim, so `createMnRef()` refs
 * read the same prose as the JSX attributes.
 */
export interface TopographicBackgroundSignals {
  /**
   * Backdrop color behind the contour map — any CSS color (8-digit hex adds
   * alpha).
   */
  color0: StringSignalMethod;
  /**
   * Palette stop 1 — low-elevation contour color (deep coral). Any CSS color;
   * color1–color3 default to the original coral → amber → gold ramp.
   */
  color1: StringSignalMethod;
  /**
   * Palette stop 2 — mid-elevation contour color (warm amber). Any CSS color
   * (8-digit hex adds alpha).
   */
  color2: StringSignalMethod;
  /**
   * Palette stop 3 — high-elevation contour color (gold). Any CSS color (8-digit
   * hex adds alpha).
   */
  color3: StringSignalMethod;
  /**
   * Number of contour levels drawn across the field (the density knob). Range
   * 2–60: higher = denser, finer rings; lower = sparse, bold topography. 14 =
   * original look.
   */
  contours: NumberSignalMethod;
  /**
   * How fast the elevation field morphs — multiplier on scene time. Range 0–1: 0
   * freezes the terrain, 0.15 = original look, 1 = fast churn.
   */
  speed: NumberSignalMethod;
  /**
   * Spatial frequency of the elevation noise, in CSS px. Range 0.001–0.01: low =
   * broad rolling hills, high = fine tight contours.
   */
  noiseScale: NumberSignalMethod;
  /**
   * Elevation-label density along the major contours. Range 0–1: 0 hides the
   * labels, 1 = original density.
   */
  labels: NumberSignalMethod;
  /**
   * Elevation-label font size in px. Range 6–24: 6 = subtle annotation, 24 = bold
   * map lettering. 9 = original.
   */
  labelSize: NumberSignalMethod;
}

/**
 * Declarative props of TopographicBackground (JSX attributes and `background(...)`
 * config literals). Carries the per-prop hover docs, mirroring the config
 * `description`s verbatim.
 */
export interface TopographicBackgroundProps {
  /**
   * Backdrop color behind the contour map — any CSS color (8-digit hex adds
   * alpha).
   */
  color0?: string;
  /**
   * Palette stop 1 — low-elevation contour color (deep coral). Any CSS color;
   * color1–color3 default to the original coral → amber → gold ramp.
   */
  color1?: string;
  /**
   * Palette stop 2 — mid-elevation contour color (warm amber). Any CSS color
   * (8-digit hex adds alpha).
   */
  color2?: string;
  /**
   * Palette stop 3 — high-elevation contour color (gold). Any CSS color (8-digit
   * hex adds alpha).
   */
  color3?: string;
  /**
   * Number of contour levels drawn across the field (the density knob). Range
   * 2–60: higher = denser, finer rings; lower = sparse, bold topography. 14 =
   * original look.
   */
  contours?: number;
  /**
   * How fast the elevation field morphs — multiplier on scene time. Range 0–1: 0
   * freezes the terrain, 0.15 = original look, 1 = fast churn.
   */
  speed?: number;
  /**
   * Spatial frequency of the elevation noise, in CSS px. Range 0.001–0.01: low =
   * broad rolling hills, high = fine tight contours.
   */
  noiseScale?: number;
  /**
   * Elevation-label density along the major contours. Range 0–1: 0 hides the
   * labels, 1 = original density.
   */
  labels?: number;
  /**
   * Elevation-label font size in px. Range 6–24: 6 = subtle annotation, 24 = bold
   * map lettering. 9 = original.
   */
  labelSize?: number;
}
