// AUTOGENERATED by packages/components/scripts/gen-background-docs.mjs.
// Single source of prose: the `description` strings in this directory's
// background.ts (never edit this file by hand — run `pnpm gen`, which the
// build/test/check scripts also run, after changing a description).
/* eslint-disable */

import { type NumberSignalMethod, type StringSignalMethod } from "@moliniani/core";

/**
 * Tween methods exposed by GroovySquaresBackground — one per declarative prop. Hover
 * docs mirror the config `description`s verbatim, so `createMnRef()` refs
 * read the same prose as the JSX attributes.
 */
export interface GroovySquaresBackgroundSignals {
  /**
   * Base square color; blends toward color1 as squares drift. Any CSS color
   * (8-digit hex adds alpha).
   */
  color0: StringSignalMethod;
  /**
   * Accent square color; squares blend between color0 and color1. Any CSS color
   * (8-digit hex adds alpha).
   */
  color1: StringSignalMethod;
  /**
   * Squares across the screen (the size knob). Range 2–40: higher = more, smaller
   * squares; lower = fewer, larger. 7.6 = original look.
   */
  density: NumberSignalMethod;
  /**
   * Spatial-variety seed. Range 1–100: near 1 = nearly uniform, high = strong
   * variance between adjacent squares.
   */
  random: NumberSignalMethod;
  /**
   * Per-square drift/wobble velocity — multiplier on scene time. Range 0–2: 0
   * freezes the pattern, 0.3 = original look.
   */
  speed: NumberSignalMethod;
}

/**
 * Declarative props of GroovySquaresBackground (JSX attributes and `background(...)`
 * config literals). Carries the per-prop hover docs, mirroring the config
 * `description`s verbatim.
 */
export interface GroovySquaresBackgroundProps {
  /**
   * Base square color; blends toward color1 as squares drift. Any CSS color
   * (8-digit hex adds alpha).
   */
  color0?: string;
  /**
   * Accent square color; squares blend between color0 and color1. Any CSS color
   * (8-digit hex adds alpha).
   */
  color1?: string;
  /**
   * Squares across the screen (the size knob). Range 2–40: higher = more, smaller
   * squares; lower = fewer, larger. 7.6 = original look.
   */
  density?: number;
  /**
   * Spatial-variety seed. Range 1–100: near 1 = nearly uniform, high = strong
   * variance between adjacent squares.
   */
  random?: number;
  /**
   * Per-square drift/wobble velocity — multiplier on scene time. Range 0–2: 0
   * freezes the pattern, 0.3 = original look.
   */
  speed?: number;
}
